### ISSUE TITLE
채팅방 입장시 메시지가 없으면 에러 발생

### ISSUE THREAD

**Issue by raccoonback** [LandvibeDev/web-chat-backend#28]
## 📝 버그 설명

- 채팅방 입장시 메시지가 없으면 에러 발생

**Comment by so3500** [comment]
# 에러 화면
![image](https://user-images.githubusercontent.com/19392136/91650829-92c10d80-eabf-11ea-9616-9ab2158c479e.png)

# 원인
```java
public List<Message> getMessagesBy(Long roomId) {
	if (!messageRepository.existsByRoomId(roomId)) {
		throw new NotFoundException(roomId); // <---
	}
	return messageRepository.findAllByRoomId(roomId);
}
```

메시지가 없을 때 빈 리스트가 반환될 것이므로 미리 검사하는 로직해서 예외를 던지는 로직은 제외해도 상관없을 듯
