### ISSUE TITLE
채팅방 입장시 메시지 리스트 조회하는 기능

### ISSUE THREAD

**Issue by raccoonback** [LandvibeDev/web-chat-backend#7]
## 🥤 추가 기능

> 채팅방 입장시 메시지 리스트 조회하는 기능 추가

**Comment by raccoonback** [comment]
## Room - Message 매핑 관계 테스트

### Message 에서 ManyToOne 한 경우

> Optional<List<Message>> findAllByRoomId(Long id);
> List<Message> messages = messageRepository.findAllByRoomId(id).get();

```sql
select message0_.id           as id1_0_,
       message0_.contents     as contents2_0_,
       message0_.created_at   as created_3_0_,
       message0_.message_type as message_4_0_,
       message0_.room_id      as room_id5_0_
from message message0_
         left outer join room room1_ on message0_.room_id = room1_.id
where room1_.id = 1;

select room0_.id as id1_1_0_, room0_.title as title2_1_0_
from room room0_
where room0_.id = 1;
```

### Room 에서 OneToMany 한 경우

> List<Message> messages = roomRepository.findById(id).get().getMessages()

```sql
select room0_.id as id1_1_0_, room0_.title as title2_1_0_
from room room0_
where room0_.id = 1;

select messages0_.room_id      as room_id5_0_0_,
       messages0_.id           as id1_0_0_,
       messages0_.id           as id1_0_1_,
       messages0_.contents     as contents2_0_1_,
       messages0_.created_at   as created_3_0_1_,
       messages0_.message_type as message_4_0_1_
from message messages0_
where messages0_.room_id = 1;
```

### 차이점
- join 유무?

**Comment by raccoonback** [comment]
### Message 에서 ManyToOne 한 경우
- Room 조회후, Message에 Room을 세팅하면 됨

```sql
select room0_.id as id1_1_0_, room0_.title as title2_1_0_
from room room0_
where room0_.id = 1;

insert into message (contents, created_at, message_type, room_id)
values (?, ?, ?, ?);
```

### Room 에서 OneToMany 한 경우
- 새로운 메시지 추가시 해당 Room에 포함된 모든 메시지를 조회해야함;;

```sql
select room0_.id as id1_1_0_, room0_.title as title2_1_0_
from room room0_
where room0_.id = 1;

select messages0_.room_id      as room_id5_0_0_,
       messages0_.id           as id1_0_0_,
       messages0_.id           as id1_0_1_,
       messages0_.contents     as contents2_0_1_,
       messages0_.created_at   as created_3_0_1_,
       messages0_.message_type as message_4_0_1_
from message messages0_
where messages0_.room_id = 1;

insert into message (contents, created_at, message_type)
values (?, ?, ?);

update message
set room_id=?
where id = ?;
```

**Comment by KeonHee** [comment]
위 경우에서 Optional을 꼭 써야할까?
  - `List<T>`의 경우 `list.isEmpty()`로 대체 가능
  - findAllByRoomId의 결과가 없으면 `list.empty()`로 체크 가능
  - findAllByRoomId의 리턴 값이 null이 아님(여기서 Optional을 쓸 이유가 없어짐)
  - 특히 `List messages = messageRepository.findAllByRoomId(id).get()` 에서 이미 Optional이 empty임을 가정하지 않고 있음. 그렇다면 Optional이 꼭 필요한가?

**Comment by raccoonback** [comment]
@KeonHee 
조회된 값이 없으면 빈 리스트로 반환해주는구나. 👍 👍   null 반환하는줄 알았어..;
`messageRepository.findAllByRoomId(id).get()` 요거는 테스트용으로 해본거라서.. empty까지 고려 안했어ㅜ 뜨허 🙀
JPA 어렵다아아

**Comment by raccoonback** [comment]
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/LocalDateTime.html

**Comment by raccoonback** [comment]
![image](https://user-images.githubusercontent.com/16451031/90313916-0e14b200-df4b-11ea-9e68-18f0742c68b9.png)
